#!/bin/bash
#
# This can be run with zsh as well if you don't have bash installed for whatever reason.

gametitle=$1

echo "Enter the 'game title' for a PS1 game"
read gametitle

cp -vr ~/.pcsxr/$gametitle\config.cfg ~/.pcsxr/pcsxr.cfg
cp -vr ~/.pcsxr/plugins/$gametitle\gpu.cfg ~/.pcsxr/plugins/gpuPeopsMesaGL.cfg
