#!/bin/bash
#
# This can be run with zsh as well if you don't have bash installed for whatever reason.

gametitle=$1
patch=$2
outputfile=$3

read -n1 -r -p "You need to have xdelta3 installed to run this script. Press any key to continue..."

echo "
What is the path to the source ROM? If source is in the current path, just provide the file name."
read gametitle

echo "
What is the path to the patch? If patch is in the current path, just provide the file name."
read patch

echo "
Provide the name and path for the outputfile (i.e. the patched copy of the ROM):"
read outputfile

xdelta3 -d -s $gametitle $patch $outputfile
